version: '3.6'
services:
  iris:
    build: 
      context: .
    command: --check-caps false
    hostname: "fullstack"
    container_name: "fullstack"
    ports: 
      - 60000:52773
    volumes:
      - ./web:/opt/coffee/csp
      - ./tests:/opt/coffee/tests
      - ./:/irisdev/app
      - ./data:/data
      - ./irisdata:/irisdata
    environment:
      - ISC_DATA_DIRECTORY=/irisdata
